{
 "title": "PNB Visualizations",
 "description": "Every Node over an hour",
 "time": { "from": "2024-03-30T04:00:00.000Z", "to": "2024-03-30T05:01:00.000Z" },
 "panels": [
  {
   "title": "External Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"External-Wind-Speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "External Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"External-Wind-Direction\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "External Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "All Node Strains",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2B-Right\" or r[\"node\"] == \"2B-Left\" or r[\"node\"] == \"2A-Left\" or r[\"node\"] == \"17B-Left\" or r[\"node\"] == \"17B-Right\" or r[\"node\"] == \"17A-Right\" or r[\"node\"] == \"2A-Right\" or r[\"node\"] == \"10A-Left\" or r[\"node\"] == \"10A-Right\" or r[\"node\"] == \"10B-Left\" or r[\"node\"] == \"10B-Right\" or r[\"node\"] == \"17A-Left\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "External Weather",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"External-Temperature\" or r[\"node\"] == \"External-Wind-Direction\" or r[\"node\"] == \"External-Wind-Speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2B-Right with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2B-Right\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2B-Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2B-Right\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2B-Left with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2B-Left\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2B-Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2B-Left\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2A-Right with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2A-Right\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2A-Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2A-Right\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2A-Left with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2A-Left\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "2A-Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"2A-Left\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "17B-Right with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17B-Right\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "17B-Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17B-Right\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "17B-Left with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17B-Left\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "17B-Left ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17B-Left\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "17A-Right with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17A-Right\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "17A-Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17A-Right\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "17A-Left with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17A-Left\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "17A-Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"17A-Left\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "10B-Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10B-Left\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "10B-Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10B-Left\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "10B-Right with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10B-Right\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "10B-Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10B-Right\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "10A-Right with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10A-Right\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "10A-Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10A-Right\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "10A-Left with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10A-Left\" or r[\"node\"] == \"External-Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "10A-Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"10A-Left\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "Complete Reading",
   "type": "timeseries",
   "description": "Test: Complete reading of every node over an hour of data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NodeStrain\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"External-Temperature\" or r[\"node\"] == \"External-Wind-Direction\" or r[\"node\"] == \"External-Wind-Speed\" or r[\"node\"] == \"2B-Right\" or r[\"node\"] == \"2B-Left\" or r[\"node\"] == \"2A-Right\" or r[\"node\"] == \"2A-Left\" or r[\"node\"] == \"17B-Right\" or r[\"node\"] == \"10A-Left\" or r[\"node\"] == \"10A-Right\" or r[\"node\"] == \"10B-Left\" or r[\"node\"] == \"10B-Right\" or r[\"node\"] == \"17A-Left\" or r[\"node\"] == \"17B-Left\" or r[\"node\"] == \"17A-Right\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}