version: '3'
services:
  devcontainer:
    build: ./python-dev
    container_name: vismod-dev
    command: "sleep infinity"
    # may need to be changed for different users
    user: "1000:1000"
    volumes:
      - "..:/workspace:cached"
    working_dir: /workspace
    ports:
      - "4000:4000"
      - "5000:5000"
      
  influx:
    image: influxdb:latest
    container_name: influx
    ports:
    - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=zatan
      - DOCKER_INFLUXDB_INIT_PASSWORD=Zatan123!
      - DOCKER_INFLUXDB_INIT_ORG=zatan
      - DOCKER_INFLUXDB_INIT_BUCKET=dev
    volumes:
     # the config volume exists because the admin token is written there on first use
      - influx_config:/etc/influxdb2
      - influx_storage:/var/lib/influxdb2

volumes:
  influx_storage:
  influx_config:
  workspace:
