# Runs on any push or PR
# checks basic tests, lints, and formatting

name: Tests and Static Analysis

on: [push, pull_request]

jobs:
  format_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    - name: Check if code has been formatted
      run: hatch run black --check ./src ./tests
    - name: Flake8 lints
      run: hatch run lint
    - name: Run unit tests
      run: hatch run test
    - name: Check that package can build
      run: hatch build
