---
# Runs when we push to master (merge PR).
# Deploys Ansible Playbook to set up server
# and Python services.

name: "DeployProject"
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
