---
# Runs when we push to master (merge PR).
# Deploys Ansible Playbook to set up server
# and Python services.

name: "DeployProject"
on:
  push:
    branches:
      - main
jobs:
  deploy_ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: "infrastructure/deploy-prod.yaml"
          directory: "infrastructure"
          key: ${{secrets.PROD_SERVER_KEY}}
          options: |
            --extra-vars www_location = ${{secrets.PROD_SERVER_HOSTNAME}}
